"""4-hourly market update (context, NOT trade calls). Every number is computed here from Binance
public USDT-M perp klines; nothing is generated by a language model, so nothing can be invented.

Per coin: last closed 4h close, 4h and 24h change, RSI(14) and MACD(12,26,9) histogram on 4h bars,
and whether the daily close is above its 100-day average. Breadth counts strong / weak coins.
Holdings of each running strategy version are read from its paper ledger.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import numpy as np
import pandas as pd
import requests

from engine.live.feed import KLINE_URL, FeedError, get_json, parse_klines
from engine.live.telegram import DISCLAIMER

COINS = ["BTC", "ETH", "SOL", "BNB", "XRP", "DOGE", "ADA", "AVAX", "LINK", "HYPE"]


def rsi(close: pd.Series, n: int = 14) -> pd.Series:
    d = close.diff()
    up = d.clip(lower=0).ewm(alpha=1 / n, adjust=False, min_periods=n).mean()
    dn = (-d.clip(upper=0)).ewm(alpha=1 / n, adjust=False, min_periods=n).mean()
    out = 100 - 100 / (1 + up / dn.where(dn > 0))
    return out.mask(dn.eq(0) & up.notna(), 100.0)       # no losses in the window -> RSI 100


def macd_hist(close: pd.Series, fast: int = 12, slow: int = 26, sig: int = 9) -> pd.Series:
    line = close.ewm(span=fast, adjust=False).mean() - close.ewm(span=slow, adjust=False).mean()
    return line - line.ewm(span=sig, adjust=False).mean()


def closed_klines(session: requests.Session, symbol: str, interval: str, bar: pd.Timedelta, limit: int,
                  now: pd.Timestamp, quote: str = "USDT") -> pd.DataFrame:
    rows = get_json(session, KLINE_URL["perp"], {"symbol": f"{symbol}{quote}", "interval": interval,
                                                 "limit": limit})
    df = parse_klines(rows, now + pd.Timedelta(hours=1) - bar)   # keep bars with open + bar <= now
    return df.set_index("ts") if "ts" in df.columns else df


@dataclass
class CoinRow:
    symbol: str
    close: float
    chg_4h: float
    chg_24h: float
    rsi: float
    macd_hist: float
    above_100d: bool | None

    @property
    def state(self) -> str:
        if self.rsi >= 55 and self.macd_hist > 0:
            return "strong"
        if self.rsi <= 45 and self.macd_hist < 0:
            return "weak"
        return "neutral"


def coin_row(session: requests.Session, sym: str, now: pd.Timestamp) -> CoinRow:
    h4 = closed_klines(session, sym, "4h", pd.Timedelta(hours=4), 200, now)
    d1 = closed_klines(session, sym, "1d", pd.Timedelta(days=1), 120, now)
    c = h4["close"].astype(float)
    if len(c) < 30:
        raise FeedError(f"{sym}: only {len(c)} closed 4h bars")
    dc = d1["close"].astype(float)
    above = bool(dc.iloc[-1] > dc.iloc[-100:].mean()) if len(dc) >= 100 else None
    return CoinRow(sym, float(c.iloc[-1]), float(c.iloc[-1] / c.iloc[-2] - 1),
                   float(c.iloc[-1] / c.iloc[-7] - 1), float(rsi(c).iloc[-1]),
                   float(macd_hist(c).iloc[-1]), above)


def holdings_line(name: str, qty: dict[str, dict[str, float]]) -> str:
    longs = sorted(s for m in qty.values() for s, q in m.items() if q > 0)
    shorts = sorted(s for m in qty.values() for s, q in m.items() if q < 0)
    parts = []
    if longs:
        parts.append("long " + ", ".join(longs))
    if shorts:
        parts.append("short " + ", ".join(shorts))
    return f"  {name}: " + ("; ".join(parts) if parts else "flat (all cash)")


def _px(x: float) -> str:
    if x >= 1:
        return f"{x:,.2f}"
    return np.format_float_positional(x, precision=4, unique=False, fractional=False, trim="-")


def format_update(asof: pd.Timestamp, rows: list[CoinRow], holdings: list[str], errors: list[str]) -> str:
    strong = [r.symbol for r in rows if r.state == "strong"]
    weak = [r.symbol for r in rows if r.state == "weak"]
    out = [f"Market update - 4h candle closed {asof:%Y-%m-%d %H:%M} UTC", ""]
    for r in rows:
        trend = "" if r.above_100d is None else (" | above 100d avg" if r.above_100d else " | below 100d avg")
        out.append(f"{r.symbol:5s} {_px(r.close):>11s}  4h {r.chg_4h:+.1%}  24h {r.chg_24h:+.1%}  "
                   f"RSI {r.rsi:.0f}  MACD {'+' if r.macd_hist > 0 else '-'}{trend}")
    out += ["", f"Breadth: {len(strong)} strong, {len(weak)} weak, "
                f"{len(rows) - len(strong) - len(weak)} neutral (of {len(rows)})"]
    if holdings:
        out += ["", "Our paper strategies hold:", *holdings]
    if errors:
        out += ["", "Missing data: " + "; ".join(errors)]
    out += ["", "Market context only - not a buy or sell call.", DISCLAIMER]
    return "\n".join(out)


def build_update(session: requests.Session, now: pd.Timestamp, coins: list[str],
                 ledgers: list[tuple[str, dict[str, dict[str, float]]]]) -> tuple[str, dict[str, Any]]:
    rows: list[CoinRow] = []
    errors: list[str] = []
    for s in coins:
        try:
            rows.append(coin_row(session, s, now))
        except (FeedError, KeyError, IndexError) as e:
            errors.append(f"{s}: {e}")
    asof = now.floor("4h")                  # close time of the last completed 4h candle
    text = format_update(asof, rows, [holdings_line(n, q) for n, q in ledgers], errors)
    return text, {"asof": asof.isoformat(), "rows": [r.__dict__ | {"state": r.state} for r in rows],
                  "errors": errors}
